spring:
  flyway:
    locations: classpath:db/migration
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      username: postgres
      password: admin
      schema: "gps"

